### ISSUE TITLE
You can use private even with github free

### ISSUE THREAD

**Issue by Wabri** [jesseduffield/wisdom#1]
Even with free account you can have unlimited private repositories, I quote a paragraf from the [about repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories#about-repositories):
> With GitHub Free for user accounts and organizations, you can work with unlimited collaborators on unlimited public repositories with a full feature set, or unlimited private repositories with a limited feature set.

I am curious, so I would prefer it to be public 😄

**Comment by jesseduffield** [comment]
Ah I should have mentioned: I intend to use the wiki feature of github, which itself indeed requires the paid version. Thanks anyway!
